base_map = {
    'video': 'Відео',
    'video-background-effect-horizontal': 'Горизонтальний ефект відеотла',
    'video-bluetooth': 'Відео через Bluetooth',
    'video-camera': 'Відеокамера',
    'video-camera-record': 'Запис відео',
    'video-camera-vintage': 'Ретро відеокамера',
    'video-chat': 'Відеочат',
    'video-clip': 'Відеокліп',
    'video-clip-multiple': 'Набір відеокліпів',
    'video-clip-off': 'Відеокліп вимкнено',
    'video-clip-optimize': 'Оптимізація відеокліпу',
    'video-clip-wand': 'Відеокліп із чарівною паличкою',
    'video-conference': 'Відеоконференція',
    'video-cross': 'Відео з хрестиком',
    'video-file': 'Відеофайл',
    'video-link': 'Відеопосилання',
    'video-multiple': 'Кілька відео',
    'video-off': 'Відео вимкнено',
    'video-one': 'Відео (варіант 1)',
    'video-people': 'Групове відео',
    'video-person': 'Відео з людиною',
    'video-person-call': 'Відеодзвінок',
    'video-person-clock': 'Відеозустріч за розкладом',
    'video-person-off': 'Відео з людиною вимкнено',
    'video-person-pulse': 'Відеодзвінок із пульсом',
    'video-person-sparkle': 'Відеодзвінок із сяйвом',
    'video-person-sparkle-off': 'Відеодзвінок із сяйвом вимкнено',
    'video-person-star': 'Відеодзвінок із зіркою',
    'video-person-star-off': 'Відеодзвінок із зіркою вимкнено',
    'video-play-pause': 'Кнопка «Відтворити/Пауза»',
    'video-player': 'Відеоплеєр',
    'video-prohibited': 'Відео заборонено',
    'video-projector': 'Відеопроєктор',
    'video-question-mark': 'Відео зі знаком питання',
    'video-recording': 'Записування відео',
    'video-security': 'Відеоспостереження',
    'video-settings': 'Налаштування відео',
    'video-slash': 'Перекреслене відео',
    'video-switch': 'Перемикач відео',
    'video-sync': 'Синхронізація відео',
    'video-two': 'Відео (варіант 2)',
    'video-usb': 'Відео через USB',
    'videocamera-one': 'Відеокамера (варіант 1)',
    'videotape': 'Відеокасета',
    'viencharts': 'Viencharts',
    'view': 'Перегляд',
    'view-alt': 'Альтернативний перегляд',
    'view-columns': 'Перегляд колонок',
    'view-desktop': 'Перегляд на компʼютері',
    'view-desktop-mobile': 'Перегляд на компʼютері та телефоні',
    'view-grid-card': 'Перегляд картками',
    'view-grid-detail': 'Перегляд деталізованою сіткою',
    'view-grid-list': 'Перегляд списком',
    'view-hide': 'Прихований перегляд',
    'view-horizont': 'Горизонтальний перегляд',
    'view-structure-down': 'Структура вниз',
    'view-structure-up': 'Структура вгору',
    'vigo': 'Vigo',
    'vihara': 'Віхара',
    'vimeo-circle': 'Vimeo у колі',
    'vimeo-square': 'Vimeo у квадраті',
    'vine-circle': 'Vine у колі',
    'vip-consume': 'VIP-споживання',
    'vip-one': 'VIP (варіант 1)',
    'virtual-network': 'Віртуальна мережа',
    'virtual-network-toolbox': 'Інструменти віртуальної мережі',
    'virtual-reality-glasses': 'Окуляри віртуальної реальності',
    'visa-square': 'Visa у квадраті',
    'viva-engage-logo': 'Viva Engage',
    'vnv': 'VNV',
    'voice-check': 'Голос із позначкою',
    'voice-circle': 'Голос у колі',
    'voice-input': 'Голосове введення',
    'voice-lock-circle': 'Голосовий замок у колі',
    'voice-message': 'Голосове повідомлення',
    'voice-off': 'Голос вимкнено',
    'voice-one': 'Голос (варіант 1)',
    'voice-square': 'Голос у квадраті',
    'voice-xmark': 'Голос із хрестиком',
    'voicemail': 'Голосова пошта',
    'voicemail-arrow-back': 'Голосова пошта — стрілка назад',
    'voicemail-arrow-forward': 'Голосова пошта — стрілка вперед',
    'voicemail-arrow-subtract': 'Голосова пошта — мінус',
    'voicemail-shield': 'Голосова пошта з щитом',
    'voicemail-subtract': 'Голосова пошта — відняти',
    'volkswagen': 'Volkswagen',
    'volleyball-ball': 'Волейбольний мʼяч',
    'voltage': 'Напруга',
    'volume-circle': 'Гучність у колі',
    'volume-down': 'Зменшення гучності',
    'volume-down-circle': 'Гучність мінус у колі',
    'volume-down-square': 'Гучність мінус у квадраті',
    'volume-mute-circle': 'Без звуку у колі',
    'volume-mute-square': 'Без звуку у квадраті',
    'volume-notice': 'Сповіщення про звук',
    'volume-off': 'Звук вимкнено',
    'volume-remove': 'Прибрати звук',
    'volume-square': 'Гучність у квадраті',
    'volume-up': 'Збільшення гучності',
    'volume-up-circle': 'Гучність плюс у колі',
    'volume-up-square': 'Гучність плюс у квадраті',
    'volume-zero': 'Нульова гучність',
    'vote': 'Голосування',
    'vote-yea': 'Голос «за»',
    'vr-cardboard': 'Картонний VR-шолом',
    'vr-tag': 'VR-тег',
    'vs-code': 'VS Code',
    'waist': 'Талія',
    'waistline': 'Лінія талії',
    'walkie-talkie': 'Радіостанція',
    'wallet': 'Гаманець',
    'wallet-alt': 'Альтернативний гаманець',
    'wallet-cards': 'Гаманець із картками',
    'wallet-credit-card': 'Картка-гаманець',
    'wallet-minimal': 'Мінімалістичний гаманець',
    'wallet-one': 'Гаманець (варіант 1)',
    'wallet-three': 'Гаманець (варіант 3)',
    'wallet-two': 'Гаманець (варіант 2)',
    'wallpaper': 'Шпалери',
    'wand': 'Чарівна паличка',
    'wand-sparkles': 'Чарівна паличка з іскрами',
    'warehouse-into': 'Заїзд на склад',
    'warehouse-pre': 'Підготовка складу',
    'warehousing': 'Складування',
    'warning': 'Попередження',
    'warning-circle': 'Попередження у колі',
    'warning-hexagon': 'Попередження в шестикутнику',
    'warning-lock-open': 'Попередження з відкритим замком',
    'warning-multiple': 'Кілька попереджень',
    'warning-rhomb': 'Попередження в ромбі',
    'warning-rhomb-multiple': 'Кілька ромбів попередження',
    'warning-shield': 'Попередження на щиті',
    'warning-square': 'Попередження в квадраті',
    'warning-triangle': 'Попереджувальний трикутник',
    'warning-window': 'Попередження у вікні',
    'washer': 'Пральна машина',
    'washing-machine-one': 'Пральна машина (варіант 1)',
    'watch': 'Годинник',
    'watch-activity': 'Годинник активності',
    'watch-alarm': 'Годинник із будильником',
    'watch-alt': 'Альтернативний годинник',
    'watch-bars': 'Годинник зі смужками',
    'watch-beat': 'Годинник-пульсометр',
    'watch-charging': 'Заряджання годинника',
    'watch-loader': 'Завантаження на годиннику',
    'watch-loop': 'Петля на годиннику',
    'watch-music': 'Годинник із музикою',
    'watch-off-loop': 'Годинник вимкнено (петля)',
    'watch-off-twotone-loop': 'Годинник вимкнено (двокольорова петля)',
    'watch-one': 'Годинник (варіант 1)',
    'watch-square-alarm': 'Квадратний годинник із будильником',
    'watch-table': 'Настільний годинник',
    'watch-text': 'Годинник із текстом',
    'watch-twotone-loop': 'Годинник (двокольорова петля)',
    'water': 'Вода',
    'water-bathing': 'Купання у воді',
    'water-drop': 'Крапля води',
    'water-fish': 'Риба у воді',
    'water-level': 'Рівень води',
    'water-no': 'Заборона води',
    'water-pistol': 'Водяний пістолет',
    'water-plant': 'Полив рослини',
    'water-rate': 'Витрата води',
    'water-rate-two': 'Витрата води (варіант 2)',
    'water-sunbathing': 'Засмагання на воді',
    'waterfall': 'Водоспад',
    'waterfalls-h': 'Водоспад (горизонтальний)',
    'waterfalls-v': 'Водоспад (вертикальний)',
    'watering-soil': 'Зволоження ґрунту',
    'watermelon-one': 'Кавун (варіант 1)',
    'waterpolo-one': 'Водне поло (варіант 1)',
    'wave-circle': 'Хвиля в колі',
    'waves-birds': 'Хвилі з птахами',
    'waves-ladder': 'Хвилі-сходи',
    'waves-left': 'Хвилі ліворуч',
    'waves-right': 'Хвилі праворуч',
    'waves-shark-fin': 'Хвилі з плавцем акули',
    'waypoints': 'Точки маршруту',
    'we-chat': 'WeChat',
    'weary-cat': 'Виснажений кіт',
    'weather-blowing-snow': 'Заметіль',
    'weather-cloudy': 'Хмарна погода',
    'weather-cloudy-loop': 'Цикл хмарності',
    'weather-drizzle': 'Мряка',
    'weather-duststorm': 'Пилова буря',
    'weather-fog': 'Туман',
    'weather-hail-day': 'Град удень',
    'weather-hail-night': 'Град уночі',
    'weather-haze': 'Серпанок',
    'weather-moon': 'Місяць',
    'weather-moon-off': 'Місяць вимкнено',
    'weather-partly-cloudy-day': 'Мінлива хмарність (день)',
    'weather-partly-cloudy-night': 'Мінлива хмарність (ніч)',
    'weather-rain': 'Дощ',
    'weather-rain-showers-day': 'Зливи вдень',
    'weather-rain-showers-night': 'Зливи вночі',
    'weather-rain-snow': 'Мокрий сніг',
    'weather-snow': 'Сніг',
    'weather-snow-shower-day': 'Снігопад удень',
    'weather-snow-shower-night': 'Снігопад уночі',
    'weather-snowflake': 'Сніжинка',
    'weather-squalls': 'Шквали',
    'weather-sunny': 'Сонячно',
    'weather-sunny-high': 'Спека',
    'weather-sunny-low': 'Сонячно й прохолодно',
    'weather-thunderstorm': 'Гроза',
    'web-asset': 'Вебактив',
    'web-browser-screen': 'Екран браузера',
    'web-page': 'Вебсторінка',
    'web-window': 'Вебвікно',
    'web-window-energy-consumption': 'Вебвікно — споживання енергії',
    'web-window-xmark': 'Вебвікно з хрестиком',
    'webcam-cancelled': 'Вебкамера скасована',
    'webp-format': 'Формат WebP',
    'website': 'Вебсайт',
    'website-alt': 'Альтернативний вебсайт',
    'week': 'Тиждень',
    'weibo-logo': 'Weibo',
    'weight-alt': 'Альтернативна вага',
    'weight-hanging': 'Підвісна гиря',
    'weight-machine': 'Підлогові ваги',
    'weightlifting': 'Важка атлетика',
    'weixin-cards-offers': 'WeChat — картки та пропозиції',
    'weixin-favorites': 'WeChat Вибране',
    'weixin-games': 'WeChat Ігри',
    'weixin-market': 'WeChat Маркет',
    'weixin-mini-app': 'WeChat мінідодаток',
    'weixin-people-nearby': 'WeChat — люди поруч',
    'weixin-scan': 'WeChat Сканування',
    'weixin-search': 'WeChat Пошук',
    'weixin-shake': 'WeChat Shake',
    'weixin-top-stories': 'WeChat Топ-історії',
    'whale-narwhal': 'Нарвал',
    'whatsapp-square': 'WhatsApp у квадраті',
    'wheelbarrow': 'Будівельна тачка',
    'wheelbarrow-empty': 'Порожня тачка',
    'wheelchair-access': 'Доступність для візка',
    'whirlwind': 'Вихор',
    'whisk-fork-knife': 'Віничок, виделка й ніж',
    'whisks': 'Вінчики',
    'whistling': 'Свист',
    'white-cane': 'Біла тростина',
    'white-flag': 'Білий прапор',
    'white-haired': 'Біле волосся',
    'white-heart': 'Біле серце',
    'whiteboard': 'Дошка',
    'whiteboard-off': 'Дошка вимкнена',
    'whmcs': 'WHMCS',
    'whole-site-accelerator': 'Прискорювач сайту',
    'widget': 'Віджет',
    'widget-add': 'Додати віджет',
    'widget-alt': 'Альтернативний віджет',
    'wifi-1': 'Wi‑Fi 1 смуга',
    'wifi-2': 'Wi‑Fi 2 смуги',
    'wifi-3': 'Wi‑Fi 3 смуги',
    'wifi-4': 'Wi‑Fi 4 смуги',
    'wifi-abnormal': 'Нестабільний Wi‑Fi',
    'wifi-close': 'Закрити Wi‑Fi',
    'wifi-high': 'Потужний Wi‑Fi',
    'wifi-lock': 'Wi‑Fi під замком',
    'wifi-low': 'Слабкий Wi‑Fi',
    'wifi-off': 'Wi‑Fi вимкнено',
    'wifi-pen': 'Wi‑Fi з ручкою',
    'wifi-protected': 'Захищений Wi‑Fi',
    'wifi-settings': 'Налаштування Wi‑Fi',
    'wifi-signal-none': 'Немає сигналу Wi‑Fi',
    'wifi-tag': 'Тег Wi‑Fi',
    'wifi-warning': 'Попередження Wi‑Fi',
    'wifi-xmark': 'Wi‑Fi із хрестиком',
    'wifi-zero': 'Нульовий Wi‑Fi',
    'wikipedia-w': 'Wikipedia W',
    'wind-arrow-down': 'Вітер униз',
    'windmill-one': 'Вітряк (варіант 1)',
    'windmill-two': 'Вітряк (варіант 2)',
    'window': 'Вікно',
    'window-ad': 'Рекламне вікно',
    'window-ad-off': 'Реклама у вікні вимкнена',
    'window-ad-person': 'Рекламне вікно з користувачем',
    'window-apps': 'Вікно з програмами',
    'window-arrow-up': 'Вікно зі стрілкою вгору',
    'window-brush': 'Вікно з пензлем',
    'window-bullet-list': 'Вікно зі списком',
    'window-bullet-list-add': 'Вікно — додати в список',
    'window-check': 'Вікно з позначкою',
    'window-column-one-fourth-left': 'Вікно з лівою чвертю',
    'window-column-one-fourth-left-focus-left': 'Фокус на лівій чверті вікна',
    'window-column-one-fourth-left-focus-top': 'Фокус верхньої лівої чверті',
    'window-console': 'Консольне вікно',
    'window-database': 'Вікно бази даних',
    'window-dev-edit': 'Вікно редагування для девелопера',
    'window-dev-tools': 'Вікно інструментів розробника',
    'window-edit': 'Вікно редагування',
    'window-fingerprint': 'Вікно з відбитком',
    'window-header-horizontal': 'Горизонтальний заголовок вікна',
    'window-header-horizontal-off': 'Вікно без горизонтального заголовка',
    'window-header-vertical': 'Вертикальний заголовок вікна',
    'window-inprivate': 'Приватне вікно',
    'window-inprivate-account': 'Приватне вікно з акаунтом',
    'window-location-target': 'Вікно з мішенню',
    'window-lock': 'Вікно під замком',
    'window-maximize': 'Розгорнуте вікно',
    'window-minimize': 'Згорнуте вікно',
    'window-multiple': 'Декілька вікон',
    'window-multiple-swap': 'Обмін вікнами',
    'window-new': 'Нове вікно',
    'window-no-access': 'Вікно без доступу',
    'window-play': 'Вікно програвача',
    'window-restore': 'Відновити вікно',
    'window-settings': 'Налаштування вікна',
    'window-shield': 'Захищене вікно',
    'window-tabs': 'Вікно з вкладками',
    'window-text': 'Текстове вікно',
    'window-wrench': 'Вікно з ключем',
    'window-xmark': 'Вікно з хрестиком',
    'wine-bottle': 'Пляшка вина',
    'wine-glass-alt': 'Винний келих (альтернативний)',
    'wine-glass-bottle': 'Вино — пляшка й келих',
    'wine-off': 'Вино заборонено',
    'wingsuit-flying': 'Політ у вінгсьюті',
    'winking-face': 'Підморгуюче обличчя',
    'winking-face-with-open-eyes': 'Підморгування з відкритими очима',
    'winter': 'Зима',
    'wizards-of-the-coast': 'Wizards of the Coast',
    'wlan-off': 'WLAN вимкнено',
    'wlan-strength': 'Рівень WLAN',
    'wlan-strength-1-lock': 'WLAN рівень 1 із замком',
    'wlan-strength-2-lock': 'WLAN рівень 2 із замком',
    'wlan-strength-3-lock': 'WLAN рівень 3 із замком',
    'wlan-warning': 'Попередження WLAN',
    'wolf': 'Вовк',
    'wolf-pack-battalion': 'Wolf Pack Battalion',
}
